### ISSUE TITLE
b'/var/lib/libvirt/images/img-builder-8mjag2kt'  is missing 

### ISSUE THREAD

**Issue by laoyin** [sapan2211/maas-image-builder#1]
i use maas-image-builder R64, and my command  
  "maas-image-builder  -o /home/yin/maas-image-builder/    -a amd64 rhel   --rhel-iso /home/yin/maas-image-builder/rhel-server-7.5-x86_64-dvd.iso  "

but, i got this error, would you give me some advice, i will appreciate it.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maas_image_builder-1.0.2-py3.6.egg/mib/core.py", line 87, in execute
    builder.build_image(args)
  File "/usr/local/lib/python3.6/dist-packages/maas_image_builder-1.0.2-py3.6.egg/mib/builders/rhel.py", line 166, in build_image
    with utils.tempdir() as workdir:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/maas_image_builder-1.0.2-py3.6.egg/mib/utils.py", line 183, in tempdir
    path = tempfile.mkdtemp(suffix, prefix, location)
  File "/usr/lib/python3.6/tempfile.py", line 507, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: b'/var/lib/libvirt/images/img-builder-8mjag2kt'

**Comment by laoyin** [comment]
sorry， i miss install libvirt，  and when i installed ，
i got another error ， i am a beginer from learning maas, i am so sorry to bother you.

mount: /var/lib/libvirt/images/img-builder-1mlem3f_/iso: WARNING: device write-protected, mounted read-only.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maas_image_builder-1.0.2-py3.6.egg/mib/core.py", line 87, in execute
    builder.build_image(args)
  File "/usr/local/lib/python3.6/dist-packages/maas_image_builder-1.0.2-py3.6.egg/mib/builders/rhel.py", line 170, in build_image
    output_dir = self.copy_iso(workdir, iso_dir)
  File "/usr/local/lib/python3.6/dist-packages/maas_image_builder-1.0.2-py3.6.egg/mib/builders/rhel.py", line 114, in copy_iso
    shutil.copytree(iso_dir, output)
  File "/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('/var/lib/libvirt/images/img-builder-1mlem3f_/iso/Packages/parted-3.1-29.el7.x86_64.rpm', '/var/lib/libvirt/images/img-builder-1mlem3f_/output/Packages/parted-3.1-29.el7.x86_64.rpm', '[Errno 5] Input/output error'), ('/var/lib/libvirt/images/img-builder-1mlem3f_/iso/Packages/passivetex-1.25-17.el7.noarch.rpm', '/var/lib/libvirt/images/img-builder-1mlem3f_/output/Packages/passivetex-1.25-17.el7.noarch.rpm', '[Errno 5] Input/output error'), ('/var/lib/libvirt/images/img-builder-1mlem3f_/iso/Packages/passwd-0.79-4.el7.x86_64.rpm', '/var/lib/libvirt/images/img-builder-1mlem3f_/output/Packages/passwd-0.79-4.el7.x86_64.rpm', '[Errno 5] Input/output error'), ('/var/lib/libvirt/images/img-builder-1mlem3f_/iso/Packages/patch-2.7.1-8.el7.x86_64.rpm', '/var/lib/libvirt/images/img-builder-1mlem3f_/output/Packages/patch-2.7.1-8.el7.x86_64.rpm', '[Errno 5] Input/output error'), ('/var/lib/libvirt/images/img-builder-1mlem3f_/iso/Packages/patchutils-0.3.3-4.el7.x86_64.rpm', '/var/lib/libvirt/images/img-builder-1mlem3f_/output/Packages/patchutils-0.3.3-4.el7.x86_64.rpm'
